In [1]:
%pip install streamlit
%pip install openpyxl
%pip install Sastrawi
%pip install scikit-learn
%pip install nltk
%pip install imbalanced-learn
%pip install plotly

Requirement already satisfied: streamlit in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (1.57.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (6.1.0)
Requirement already satisfied: blinker<2,>=1.5.0 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (7.1.3)
Requirement already satisfied: click<9,>=7.0 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (8.4.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (3.1.50)
Requirement already satisfied: numpy<3,>=1.23 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (2.4.6)
Requirement already satisfied: packaging>=20 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (26.2)
Requirement already satisfied: pandas<4,>=1.4.0 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (3.0.3)
Requirement already satisfied: pillow<13,>=7.1.0 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (11.3.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (0.9.2)
Requirement already satisfied: protobuf<8,>=3.20 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (7.35.0)
Requirement already satisfied: pyarrow>=7.0 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (24.0.0)
Requirement already satisfied: requests<3,>=2.27 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (2.34.2)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (4.15.0)
Requirement already satisfied: starlette>=0.40.0 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (1.0.0)
Requirement already satisfied: uvicorn>=0.30.0 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (0.47.0)
Requirement already satisfied: httptools>=0.6.3 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (0.7.1)
Requirement already satisfied: anyio>=4.0.0 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (4.13.0)
Requirement already satisfied: python-multipart>=0.0.10 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (0.0.29)
Requirement already satisfied: websockets>=12.0.0 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (16.0)
Requirement already satisfied: itsdangerous>=2.1.2 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=2.4.0 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.21.2)
Requirement already satisfied: colorama in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas<4,>=1.4.0->streamlit) (2026.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests<3,>=2.27->streamlit) (3.15)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests<3,>=2.27->streamlit) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests<3,>=2.27->streamlit) (2026.5.20)
Requirement already satisfied: MarkupSafe>=2.0 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)
Requirement already satisfied: six>=1.5 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)
Requirement already satisfied: h11>=0.8 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from uvicorn>=0.30.0->streamlit) (0.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: openpyxl in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: Sastrawi in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (1.0.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: scikit-learn in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (2.4.6)
Requirement already satisfied: scipy>=1.10.0 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: nltk in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.9.4)
Requirement already satisfied: click in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nltk) (8.4.0)
Requirement already satisfied: joblib in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nltk) (2026.5.9)
Requirement already satisfied: tqdm in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nltk) (4.67.3)
Requirement already satisfied: colorama in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: imbalanced-learn in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (0.14.1)
Requirement already satisfied: numpy<3,>=1.25.2 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from imbalanced-learn) (2.4.6)
Requirement already satisfied: scipy<2,>=1.11.4 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from imbalanced-learn) (1.17.1)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from imbalanced-learn) (1.8.0)
Requirement already satisfied: sklearn-compat<0.2,>=0.1.5 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from imbalanced-learn) (0.1.5)
Requirement already satisfied: joblib<2,>=1.2.0 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from imbalanced-learn) (1.5.3)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from imbalanced-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: plotly in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (6.7.0)
Requirement already satisfied: narwhals>=1.15.1 in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from plotly) (2.21.2)
Requirement already satisfied: packaging in c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages (from plotly) (26.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
import nltk

nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\acer\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\acer\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [7]:
import streamlit as st
import pandas as pd
import numpy as np
import re
import pickle
import nltk

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

from sklearn.feature_extraction.text import TfidfVectorizer

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical

In [8]:
df = pd.read_excel("DATASET JUDUL SKRIPSI fiks (1).xlsx")
df.head()

                                       Judul Skripsi  LABEL
0  ANALISA PENGGUNAAN BIODIESEL MINYAK DAUN NILAM...      0
1  ANALISIS KONDISI JALAN DAN PENGARUHNYA TERHADA...      0
2  ANALISIS SIFAT MEKANIK BATA RINGAN CLC AKIBAT ...      0
3  EVALUASI POTENSI LOKASI STASIUN PADA KORIDOR K...      0
4  ANALISIS AMENITAS DAN AKSESIBILITAS JALAN WAY ...      0

In [9]:
def cleaning(text):
    text = str(text)
    text = re.sub(r'http\S+', '', text)
    text = re.sub(r'www\S+', '', text)
    text = re.sub(r'[^A-Za-z\s]', '', text)
    text = text.strip()
    return text


df['cleaning'] = df['Judul Skripsi'].apply(cleaning)

In [10]:
pd.DataFrame({
    'Teks Asli': df['Judul Skripsi'].head(),
    'Hasil Cleaning': df['cleaning'].head()
})

,Teks Asli,Hasil Cleaning
0,ANALISA PENGGUNAAN BIODIESEL MINYAK DAUN NILAM...,ANALISA PENGGUNAAN BIODIESEL MINYAK DAUN NILAM...
1,ANALISIS KONDISI JALAN DAN PENGARUHNYA TERHADA...,ANALISIS KONDISI JALAN DAN PENGARUHNYA TERHADA...
2,ANALISIS SIFAT MEKANIK BATA RINGAN CLC AKIBAT ...,ANALISIS SIFAT MEKANIK BATA RINGAN CLC AKIBAT ...
3,EVALUASI POTENSI LOKASI STASIUN PADA KORIDOR K...,EVALUASI POTENSI LOKASI STASIUN PADA KORIDOR K...
4,ANALISIS AMENITAS DAN AKSESIBILITAS JALAN WAY ...,ANALISIS AMENITAS DAN AKSESIBILITAS JALAN WAY ...

In [11]:
def case_folding(text):
    return text.lower()


df['case_folding'] = df['cleaning'].apply(case_folding)

In [12]:
pd.DataFrame({
    'Cleaning': df['cleaning'].head(),
    'Case Folding': df['case_folding'].head()
})

,Cleaning,Case Folding
0,ANALISA PENGGUNAAN BIODIESEL MINYAK DAUN NILAM...,analisa penggunaan biodiesel minyak daun nilam...
1,ANALISIS KONDISI JALAN DAN PENGARUHNYA TERHADA...,analisis kondisi jalan dan pengaruhnya terhada...
2,ANALISIS SIFAT MEKANIK BATA RINGAN CLC AKIBAT ...,analisis sifat mekanik bata ringan clc akibat ...
3,EVALUASI POTENSI LOKASI STASIUN PADA KORIDOR K...,evaluasi potensi lokasi stasiun pada koridor k...
4,ANALISIS AMENITAS DAN AKSESIBILITAS JALAN WAY ...,analisis amenitas dan aksesibilitas jalan way ...

In [13]:
def case_folding(text):
    return text.lower()


df['case_folding'] = df['cleaning'].apply(case_folding)

In [14]:
pd.DataFrame({
    'Cleaning': df['cleaning'].head(),
    'Case Folding': df['case_folding'].head()
})

,Cleaning,Case Folding
0,ANALISA PENGGUNAAN BIODIESEL MINYAK DAUN NILAM...,analisa penggunaan biodiesel minyak daun nilam...
1,ANALISIS KONDISI JALAN DAN PENGARUHNYA TERHADA...,analisis kondisi jalan dan pengaruhnya terhada...
2,ANALISIS SIFAT MEKANIK BATA RINGAN CLC AKIBAT ...,analisis sifat mekanik bata ringan clc akibat ...
3,EVALUASI POTENSI LOKASI STASIUN PADA KORIDOR K...,evaluasi potensi lokasi stasiun pada koridor k...
4,ANALISIS AMENITAS DAN AKSESIBILITAS JALAN WAY ...,analisis amenitas dan aksesibilitas jalan way ...

In [15]:
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

factory = StopWordRemoverFactory()
stopword = factory.create_stop_word_remover()

df['stopword'] = df['case_folding'].apply(lambda text: stopword.remove(str(text)))

In [16]:
pd.DataFrame({
    'Case Folding': df['case_folding'].head(),
    'Stopword Removal': df['stopword'].head()
})

,Case Folding,Stopword Removal
0,analisa penggunaan biodiesel minyak daun nilam...,analisa penggunaan biodiesel minyak daun nilam...
1,analisis kondisi jalan dan pengaruhnya terhada...,analisis kondisi jalan pengaruhnya risiko kece...
2,analisis sifat mekanik bata ringan clc akibat ...,analisis sifat mekanik bata ringan clc akibat ...
3,evaluasi potensi lokasi stasiun pada koridor k...,evaluasi potensi lokasi stasiun koridor kereta...
4,analisis amenitas dan aksesibilitas jalan way ...,analisis amenitas aksesibilitas jalan way rata...

In [17]:
factory = StemmerFactory()
stemmer = factory.create_stemmer()


def stemming(text):
    return stemmer.stem(text)


df['stemming'] = df['stopword'].apply(stemming)

pd.DataFrame({
    'Stopword Removal': df['stopword'].head(),
    'Stemming': df['stemming'].head()
})

,Stopword Removal,Stemming
0,analisa penggunaan biodiesel minyak daun nilam...,analisa guna biodiesel minyak daun nilam kerja...
1,analisis kondisi jalan pengaruhnya risiko kece...,analisis kondisi jalan pengaruh risiko celaka ...
2,analisis sifat mekanik bata ringan clc akibat ...,analisis sifat mekanik bata ringan clc akibat ...
3,evaluasi potensi lokasi stasiun koridor kereta...,evaluasi potensi lokasi stasiun koridor kereta...
4,analisis amenitas aksesibilitas jalan way rata...,analisis amenitas aksesibilitas jalan way rata...

In [18]:
def tokenisasi(text):
    return text.split()

df['tokenisasi'] = df['stemming'].apply(tokenisasi)
pd.DataFrame({
    'Stemming': df['stemming'].head(),
    'Tokenization': df['tokenisasi'].head()
})

,Stemming,Tokenization
0,analisa guna biodiesel minyak daun nilam kerja...,"[analisa, guna, biodiesel, minyak, daun, nilam..."
1,analisis kondisi jalan pengaruh risiko celaka ...,"[analisis, kondisi, jalan, pengaruh, risiko, c..."
2,analisis sifat mekanik bata ringan clc akibat ...,"[analisis, sifat, mekanik, bata, ringan, clc, ..."
3,evaluasi potensi lokasi stasiun koridor kereta...,"[evaluasi, potensi, lokasi, stasiun, koridor, ..."
4,analisis amenitas aksesibilitas jalan way rata...,"[analisis, amenitas, aksesibilitas, jalan, way..."

In [19]:
from sklearn.model_selection import train_test_split

# Re-defining X and y for clarity and to ensure they are in scope
X = df['tokenisasi'].astype(str)
y = df['LABEL']

# First split: 80% Temporary (Training + Validation), 20% Testing
X_temp, X_test, y_temp, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [20]:
# Second split: From the 80% temporary data, split 75% for Training and 25% for Validation
# This results in 0.8 * 0.75 = 0.6 (60%) for Training and 0.8 * 0.25 = 0.2 (20%) for Validation
X_train, X_val, y_train, y_val = train_test_split(
    X_temp,
    y_temp,
    test_size=0.25, # 25% of X_temp (which is 80% of total) = 20% of total
    random_state=42,
    stratify=y_temp
)

In [21]:
# Displaying the number of data points in each set
print("Jumlah data training   :", len(X_train))
print("Jumlah data validation :", len(X_val))
print("Jumlah data testing    :", len(X_test))

Jumlah data training   : 1800
Jumlah data validation : 600
Jumlah data testing    : 600

In [22]:
# Calculate total number of data points
total_data_points = len(X_train) + len(X_val) + len(X_test)

# Calculate proportions
proportion_train = (len(X_train) / total_data_points) * 100
proportion_val = (len(X_val) / total_data_points) * 100
proportion_test = (len(X_test) / total_data_points) * 100

print(f"Proportion data training   : {proportion_train:.2f}%")
print(f"Proportion data validation : {proportion_val:.2f}%")
print(f"Proportion data testing    : {proportion_test:.2f}%")

Proportion data training   : 60.00%
Proportion data validation : 20.00%
Proportion data testing    : 20.00%

In [23]:
print("Jumlah data training   :", len(X_train))
print("Jumlah data validation :", len(X_val))
print("Jumlah data testing    :", len(X_test))

Jumlah data training   : 1800
Jumlah data validation : 600
Jumlah data testing    : 600

In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer


vectorizer = TfidfVectorizer(
    max_features=3000,
    ngram_range=(1,2),
    min_df=2,
    max_df=0.9
)

# TF-IDF data training
X_train_tfidf = vectorizer.fit_transform(X_train)

# TF-IDF data validation
X_val_tfidf = vectorizer.transform(X_val)

# TF-IDF data testing
X_test_tfidf = vectorizer.transform(X_test)

In [25]:
print("Ukuran TF-IDF Training   :", X_train_tfidf.shape)
print("Ukuran TF-IDF Validation :", X_val_tfidf.shape)
print("Ukuran TF-IDF Testing    :", X_test_tfidf.shape)

Ukuran TF-IDF Training   : (1800, 3000)
Ukuran TF-IDF Validation : (600, 3000)
Ukuran TF-IDF Testing    : (600, 3000)

In [26]:
# Mengambil nama fitur/kata
feature_names = vectorizer.get_feature_names_out()

# Mengubah TF-IDF menjadi dataframe
tfidf_df = pd.DataFrame(
    X_train_tfidf.toarray(),
    columns=feature_names
)

In [27]:
# Mengambil nama fitur/kata
feature_names = vectorizer.get_feature_names_out()

# Mengubah TF-IDF menjadi dataframe
tfidf_df = pd.DataFrame(
    X_train_tfidf.toarray(),
    columns=feature_names
)

# Menampilkan tabel TF-IDF
tfidf_df.head()

,abdul,abdul moeloek,abdul rachman,abu,acnes,ada,adaptasi,adat,adi,adil,...,xgboost,yamaha,yoghurt,yoghurt susu,yolov,youtube,yuridis,zat,zea,zea mays
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [28]:
from imblearn.over_sampling import SMOTE


print("Jumlah label sebelum SMOTE")
print(y_train.value_counts())

# ====================================
# SMOTE
# ====================================

smote = SMOTE(random_state=42)

X_train_balanced, y_train_balanced = smote.fit_resample(
    X_train_tfidf,
    y_train
)


print("\nJumlah label sesudah SMOTE")
print(pd.Series(y_train_balanced).value_counts())

Jumlah label sebelum SMOTE
LABEL
0    960
1    840
Name: count, dtype: int64

Jumlah label sesudah SMOTE
LABEL
0    960
1    960
Name: count, dtype: int64

In [29]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.regularizers import l2
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

model = Sequential()

# Hidden Layer 1
model.add(Dense(
    128,
    activation='relu',
    kernel_regularizer=l2(0.003),
    input_dim=X_train_balanced.shape[1] # Corrected: Use shape from TF-IDF balanced data
))
model.add(Dropout(0.1))

# Hidden Layer 2
model.add(Dense(
    64,
    activation='relu',
    kernel_regularizer=l2(0.003)
))
model.add(Dropout(0.1))

# Hidden Layer 3
model.add(Dense(
    32,
    activation='relu',
    kernel_regularizer=l2(0.003)
))
model.add(Dropout(0.1))

# Output Layer
model.add(Dense(1, activation='sigmoid'))


model.compile(
    optimizer=Adam(learning_rate=0.0001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)


early_stop = EarlyStopping(
    monitor='val_loss',
    patience=20,
    restore_best_weights=True
)

reduce_lr = ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.5,
    patience=5,
    min_lr=0.000001
)

# ==========================================
# TRAINING
# ==========================================
history = model.fit(
    X_train_balanced.toarray(), # Corrected: Use TF-IDF balanced data converted to dense array
    y_train_balanced, # Corrected: Use balanced labels
    validation_data=(X_val_tfidf.toarray(), y_val), # Corrected: Use TF-IDF val data converted to dense array
    epochs=120,
    batch_size=64,
    callbacks=[early_stop, reduce_lr],
    verbose=1,
    shuffle=True
)

# ==========================================
# EVALUASI
# ==========================================
test_loss, test_accuracy = model.evaluate(X_test_tfidf.toarray(), y_test) # Corrected: Use TF-IDF test data converted to dense array

print("Test Loss :", test_loss)
print("Test Accuracy :", test_accuracy)

train_loss = history.history['loss']
val_loss = history.history['val_loss']


smooth_train = []
smooth_val = []

alpha = 0.92

for i in range(len(train_loss)):

    if i == 0:
        smooth_train.append(train_loss[i])
        smooth_val.append(val_loss[i])

    else:
        smooth_train.append(
            alpha * smooth_train[i-1] +
            (1-alpha) * train_loss[i]
        )

        smooth_val.append(
            alpha * smooth_val[i-1] +
            (1-alpha) * val_loss[i]
        )

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.5188 - loss: 1.7491 - val_accuracy: 0.5033 - val_loss: 1.6759 - learning_rate: 1.0000e-04
Epoch 2/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5698 - loss: 1.6134 - val_accuracy: 0.5817 - val_loss: 1.5502 - learning_rate: 1.0000e-04
Epoch 3/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6687 - loss: 1.4959 - val_accuracy: 0.7450 - val_loss: 1.4405 - learning_rate: 1.0000e-04
Epoch 4/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7802 - loss: 1.3924 - val_accuracy: 0.8517 - val_loss: 1.3424 - learning_rate: 1.0000e-04
Epoch 5/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8755 - loss: 1.2991 - val_accuracy: 0.8950 - val_loss: 1.2535 - learning_rate: 1.0000e-04
Epoch 6/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9260 - loss: 1.2134 - val_accuracy: 0.9217 - val_loss: 1.1699 - learning_rate: 1.0000e-04
Epoch 7/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9307 - loss: 1.1306 - val_accuracy: 0.9317 - val_loss: 1.0890 - learning_rate: 1.0000e-04
Epoch 8/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9458 - loss: 1.0500 - val_accuracy: 0.9367 - val_loss: 1.0078 - learning_rate: 1.0000e-04
Epoch 9/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9516 - loss: 0.9659 - val_accuracy: 0.9383 - val_loss: 0.9254 - learning_rate: 1.0000e-04
Epoch 10/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9536 - loss: 0.8827 - val_accuracy: 0.9500 - val_loss: 0.8437 - learning_rate: 1.0000e-04
Epoch 11/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9620 - loss: 0.8017 - val_accuracy: 0.9517 - val_loss: 0.7671 - learning_rate: 1.0000e-04
Epoch 12/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9635 - loss: 0.7272 - val_accuracy: 0.9567 - val_loss: 0.6990 - learning_rate: 1.0000e-04
Epoch 13/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9708 - loss: 0.6599 - val_accuracy: 0.9600 - val_loss: 0.6403 - learning_rate: 1.0000e-04
Epoch 14/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9708 - loss: 0.6055 - val_accuracy: 0.9600 - val_loss: 0.5945 - learning_rate: 1.0000e-04
Epoch 15/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9755 - loss: 0.5585 - val_accuracy: 0.9600 - val_loss: 0.5571 - learning_rate: 1.0000e-04
Epoch 16/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9760 - loss: 0.5236 - val_accuracy: 0.9667 - val_loss: 0.5267 - learning_rate: 1.0000e-04
Epoch 17/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9849 - loss: 0.4914 - val_accuracy: 0.9650 - val_loss: 0.5024 - learning_rate: 1.0000e-04
Epoch 18/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9823 - loss: 0.4659 - val_accuracy: 0.9650 - val_loss: 0.4830 - learning_rate: 1.0000e-04
Epoch 19/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9839 - loss: 0.4463 - val_accuracy: 0.9650 - val_loss: 0.4660 - learning_rate: 1.0000e-04
Epoch 20/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9880 - loss: 0.4252 - val_accuracy: 0.9650 - val_loss: 0.4512 - learning_rate: 1.0000e-04
Epoch 21/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9875 - loss: 0.4098 - val_accuracy: 0.9633 - val_loss: 0.4380 - learning_rate: 1.0000e-04
Epoch 22/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9896 - loss: 0.3957 - val_accuracy: 0.9650 - val_loss: 0.4256 - learning_rate: 1.0000e-04
Epoch 23/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9911 - loss: 0.3824 - val_accuracy: 0.9650 - val_loss: 0.4150 - learning_rate: 1.0000e-04
Epoch 24/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9911 - loss: 0.3700 - val_accuracy: 0.9633 - val_loss: 0.4053 - learning_rate: 1.0000e-04
Epoch 25/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9943 - loss: 0.3591 - val_accuracy: 0.9633 - val_loss: 0.3959 - learning_rate: 1.0000e-04
Epoch 26/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9943 - loss: 0.3483 - val_accuracy: 0.9617 - val_loss: 0.3890 - learning_rate: 1.0000e-04
Epoch 27/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9927 - loss: 0.3416 - val_accuracy: 0.9650 - val_loss: 0.3808 - learning_rate: 1.0000e-04
Epoch 28/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9937 - loss: 0.3313 - val_accuracy: 0.9600 - val_loss: 0.3736 - learning_rate: 1.0000e-04
Epoch 29/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9943 - loss: 0.3247 - val_accuracy: 0.9600 - val_loss: 0.3663 - learning_rate: 1.0000e-04
Epoch 30/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9958 - loss: 0.3178 - val_accuracy: 0.9650 - val_loss: 0.3593 - learning_rate: 1.0000e-04
Epoch 31/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9953 - loss: 0.3086 - val_accuracy: 0.9600 - val_loss: 0.3548 - learning_rate: 1.0000e-04
Epoch 32/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9958 - loss: 0.3025 - val_accuracy: 0.9650 - val_loss: 0.3478 - learning_rate: 1.0000e-04
Epoch 33/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9953 - loss: 0.2964 - val_accuracy: 0.9667 - val_loss: 0.3419 - learning_rate: 1.0000e-04
Epoch 34/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9953 - loss: 0.2908 - val_accuracy: 0.9600 - val_loss: 0.3383 - learning_rate: 1.0000e-04
Epoch 35/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9948 - loss: 0.2855 - val_accuracy: 0.9683 - val_loss: 0.3311 - learning_rate: 1.0000e-04
Epoch 36/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9974 - loss: 0.2786 - val_accuracy: 0.9650 - val_loss: 0.3293 - learning_rate: 1.0000e-04
Epoch 37/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9964 - loss: 0.2733 - val_accuracy: 0.9650 - val_loss: 0.3235 - learning_rate: 1.0000e-04
Epoch 38/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9974 - loss: 0.2671 - val_accuracy: 0.9650 - val_loss: 0.3189 - learning_rate: 1.0000e-04
Epoch 39/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9979 - loss: 0.2614 - val_accuracy: 0.9633 - val_loss: 0.3138 - learning_rate: 1.0000e-04
Epoch 40/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9979 - loss: 0.2570 - val_accuracy: 0.9633 - val_loss: 0.3109 - learning_rate: 1.0000e-04
Epoch 41/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9990 - loss: 0.2538 - val_accuracy: 0.9633 - val_loss: 0.3075 - learning_rate: 1.0000e-04
Epoch 42/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9984 - loss: 0.2491 - val_accuracy: 0.9633 - val_loss: 0.3027 - learning_rate: 1.0000e-04
Epoch 43/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9990 - loss: 0.2459 - val_accuracy: 0.9617 - val_loss: 0.2988 - learning_rate: 1.0000e-04
Epoch 44/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9984 - loss: 0.2398 - val_accuracy: 0.9633 - val_loss: 0.2965 - learning_rate: 1.0000e-04
Epoch 45/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9990 - loss: 0.2357 - val_accuracy: 0.9617 - val_loss: 0.2929 - learning_rate: 1.0000e-04
Epoch 46/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.9990 - loss: 0.2334 - val_accuracy: 0.9617 - val_loss: 0.2899 - learning_rate: 1.0000e-04
Epoch 47/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.9984 - loss: 0.2297 - val_accuracy: 0.9633 - val_loss: 0.2889 - learning_rate: 1.0000e-04
Epoch 48/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.9979 - loss: 0.2270 - val_accuracy: 0.9633 - val_loss: 0.2836 - learning_rate: 1.0000e-04
Epoch 49/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.9984 - loss: 0.2232 - val_accuracy: 0.9633 - val_loss: 0.2814 - learning_rate: 1.0000e-04
Epoch 50/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9990 - loss: 0.2182 - val_accuracy: 0.9650 - val_loss: 0.2771 - learning_rate: 1.0000e-04
Epoch 51/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9984 - loss: 0.2166 - val_accuracy: 0.9633 - val_loss: 0.2751 - learning_rate: 1.0000e-04
Epoch 52/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9979 - loss: 0.2147 - val_accuracy: 0.9633 - val_loss: 0.2720 - learning_rate: 1.0000e-04
Epoch 53/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9995 - loss: 0.2088 - val_accuracy: 0.9650 - val_loss: 0.2705 - learning_rate: 1.0000e-04
Epoch 54/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9984 - loss: 0.2081 - val_accuracy: 0.9650 - val_loss: 0.2664 - learning_rate: 1.0000e-04
Epoch 55/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9990 - loss: 0.2037 - val_accuracy: 0.9633 - val_loss: 0.2669 - learning_rate: 1.0000e-04
Epoch 56/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9979 - loss: 0.2048 - val_accuracy: 0.9617 - val_loss: 0.2623 - learning_rate: 1.0000e-04
Epoch 57/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9979 - loss: 0.1997 - val_accuracy: 0.9633 - val_loss: 0.2607 - learning_rate: 1.0000e-04
Epoch 58/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9979 - loss: 0.1981 - val_accuracy: 0.9650 - val_loss: 0.2591 - learning_rate: 1.0000e-04
Epoch 59/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9990 - loss: 0.1963 - val_accuracy: 0.9650 - val_loss: 0.2558 - learning_rate: 1.0000e-04
Epoch 60/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9984 - loss: 0.1935 - val_accuracy: 0.9650 - val_loss: 0.2543 - learning_rate: 1.0000e-04
Epoch 61/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9979 - loss: 0.1906 - val_accuracy: 0.9650 - val_loss: 0.2523 - learning_rate: 1.0000e-04
Epoch 62/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9990 - loss: 0.1901 - val_accuracy: 0.9617 - val_loss: 0.2518 - learning_rate: 1.0000e-04
Epoch 63/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9990 - loss: 0.1865 - val_accuracy: 0.9650 - val_loss: 0.2484 - learning_rate: 1.0000e-04
Epoch 64/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9995 - loss: 0.1841 - val_accuracy: 0.9667 - val_loss: 0.2491 - learning_rate: 1.0000e-04
Epoch 65/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9995 - loss: 0.1839 - val_accuracy: 0.9650 - val_loss: 0.2445 - learning_rate: 1.0000e-04
Epoch 66/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9990 - loss: 0.1814 - val_accuracy: 0.9650 - val_loss: 0.2460 - learning_rate: 1.0000e-04
Epoch 67/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9990 - loss: 0.1784 - val_accuracy: 0.9650 - val_loss: 0.2446 - learning_rate: 1.0000e-04
Epoch 68/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9979 - loss: 0.1770 - val_accuracy: 0.9633 - val_loss: 0.2412 - learning_rate: 1.0000e-04
Epoch 69/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9990 - loss: 0.1771 - val_accuracy: 0.9667 - val_loss: 0.2428 - learning_rate: 1.0000e-04
Epoch 70/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9995 - loss: 0.1742 - val_accuracy: 0.9667 - val_loss: 0.2412 - learning_rate: 1.0000e-04
Epoch 71/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9984 - loss: 0.1737 - val_accuracy: 0.9667 - val_loss: 0.2390 - learning_rate: 1.0000e-04
Epoch 72/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9990 - loss: 0.1718 - val_accuracy: 0.9650 - val_loss: 0.2394 - learning_rate: 1.0000e-04
Epoch 73/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9990 - loss: 0.1707 - val_accuracy: 0.9633 - val_loss: 0.2369 - learning_rate: 1.0000e-04
Epoch 74/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9984 - loss: 0.1707 - val_accuracy: 0.9633 - val_loss: 0.2331 - learning_rate: 1.0000e-04
Epoch 75/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9984 - loss: 0.1688 - val_accuracy: 0.9617 - val_loss: 0.2357 - learning_rate: 1.0000e-04
Epoch 76/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9995 - loss: 0.1657 - val_accuracy: 0.9650 - val_loss: 0.2307 - learning_rate: 1.0000e-04
Epoch 77/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9995 - loss: 0.1650 - val_accuracy: 0.9650 - val_loss: 0.2313 - learning_rate: 1.0000e-04
Epoch 78/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9990 - loss: 0.1631 - val_accuracy: 0.9633 - val_loss: 0.2304 - learning_rate: 1.0000e-04
Epoch 79/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9995 - loss: 0.1628 - val_accuracy: 0.9667 - val_loss: 0.2282 - learning_rate: 1.0000e-04
Epoch 80/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9990 - loss: 0.1623 - val_accuracy: 0.9667 - val_loss: 0.2274 - learning_rate: 1.0000e-04
Epoch 81/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9990 - loss: 0.1587 - val_accuracy: 0.9633 - val_loss: 0.2290 - learning_rate: 1.0000e-04
Epoch 82/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9995 - loss: 0.1587 - val_accuracy: 0.9633 - val_loss: 0.2274 - learning_rate: 1.0000e-04
Epoch 83/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9990 - loss: 0.1593 - val_accuracy: 0.9633 - val_loss: 0.2261 - learning_rate: 1.0000e-04
Epoch 84/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9995 - loss: 0.1562 - val_accuracy: 0.9633 - val_loss: 0.2272 - learning_rate: 1.0000e-04
Epoch 85/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9995 - loss: 0.1560 - val_accuracy: 0.9617 - val_loss: 0.2223 - learning_rate: 1.0000e-04
Epoch 86/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9990 - loss: 0.1559 - val_accuracy: 0.9633 - val_loss: 0.2231 - learning_rate: 1.0000e-04
Epoch 87/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9990 - loss: 0.1528 - val_accuracy: 0.9617 - val_loss: 0.2226 - learning_rate: 1.0000e-04
Epoch 88/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9990 - loss: 0.1525 - val_accuracy: 0.9650 - val_loss: 0.2196 - learning_rate: 1.0000e-04
Epoch 89/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9995 - loss: 0.1518 - val_accuracy: 0.9650 - val_loss: 0.2198 - learning_rate: 1.0000e-04
Epoch 90/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9995 - loss: 0.1513 - val_accuracy: 0.9667 - val_loss: 0.2167 - learning_rate: 1.0000e-04
Epoch 91/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9995 - loss: 0.1497 - val_accuracy: 0.9617 - val_loss: 0.2183 - learning_rate: 1.0000e-04
Epoch 92/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.1481 - val_accuracy: 0.9600 - val_loss: 0.2160 - learning_rate: 1.0000e-04
Epoch 93/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.1478 - val_accuracy: 0.9650 - val_loss: 0.2156 - learning_rate: 1.0000e-04
Epoch 94/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.1467 - val_accuracy: 0.9633 - val_loss: 0.2188 - learning_rate: 1.0000e-04
Epoch 95/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9995 - loss: 0.1461 - val_accuracy: 0.9650 - val_loss: 0.2142 - learning_rate: 1.0000e-04
Epoch 96/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.1457 - val_accuracy: 0.9667 - val_loss: 0.2125 - learning_rate: 1.0000e-04
Epoch 97/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9995 - loss: 0.1451 - val_accuracy: 0.9650 - val_loss: 0.2130 - learning_rate: 1.0000e-04
Epoch 98/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9995 - loss: 0.1442 - val_accuracy: 0.9650 - val_loss: 0.2129 - learning_rate: 1.0000e-04
Epoch 99/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9995 - loss: 0.1428 - val_accuracy: 0.9633 - val_loss: 0.2128 - learning_rate: 1.0000e-04
Epoch 100/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9990 - loss: 0.1429 - val_accuracy: 0.9633 - val_loss: 0.2120 - learning_rate: 1.0000e-04
Epoch 101/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9995 - loss: 0.1409 - val_accuracy: 0.9633 - val_loss: 0.2121 - learning_rate: 1.0000e-04
Epoch 102/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9995 - loss: 0.1404 - val_accuracy: 0.9667 - val_loss: 0.2100 - learning_rate: 1.0000e-04
Epoch 103/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.1409 - val_accuracy: 0.9667 - val_loss: 0.2105 - learning_rate: 1.0000e-04
Epoch 104/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9995 - loss: 0.1405 - val_accuracy: 0.9667 - val_loss: 0.2106 - learning_rate: 1.0000e-04
Epoch 105/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.1396 - val_accuracy: 0.9650 - val_loss: 0.2101 - learning_rate: 1.0000e-04
Epoch 106/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.1382 - val_accuracy: 0.9633 - val_loss: 0.2123 - learning_rate: 1.0000e-04
Epoch 107/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.1377 - val_accuracy: 0.9617 - val_loss: 0.2077 - learning_rate: 1.0000e-04
Epoch 108/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9995 - loss: 0.1379 - val_accuracy: 0.9617 - val_loss: 0.2105 - learning_rate: 1.0000e-04
Epoch 109/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9995 - loss: 0.1373 - val_accuracy: 0.9650 - val_loss: 0.2062 - learning_rate: 1.0000e-04
Epoch 110/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.1351 - val_accuracy: 0.9633 - val_loss: 0.2098 - learning_rate: 1.0000e-04
Epoch 111/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9990 - loss: 0.1359 - val_accuracy: 0.9667 - val_loss: 0.2054 - learning_rate: 1.0000e-04
Epoch 112/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.1344 - val_accuracy: 0.9650 - val_loss: 0.2071 - learning_rate: 1.0000e-04
Epoch 113/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9995 - loss: 0.1363 - val_accuracy: 0.9667 - val_loss: 0.2065 - learning_rate: 1.0000e-04
Epoch 114/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9995 - loss: 0.1335 - val_accuracy: 0.9633 - val_loss: 0.2063 - learning_rate: 1.0000e-04
Epoch 115/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9995 - loss: 0.1338 - val_accuracy: 0.9633 - val_loss: 0.2053 - learning_rate: 1.0000e-04
Epoch 116/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9990 - loss: 0.1333 - val_accuracy: 0.9633 - val_loss: 0.2058 - learning_rate: 1.0000e-04
Epoch 117/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9990 - loss: 0.1320 - val_accuracy: 0.9650 - val_loss: 0.2044 - learning_rate: 5.0000e-05
Epoch 118/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.1310 - val_accuracy: 0.9650 - val_loss: 0.2036 - learning_rate: 5.0000e-05
Epoch 119/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9990 - loss: 0.1327 - val_accuracy: 0.9650 - val_loss: 0.2031 - learning_rate: 5.0000e-05
Epoch 120/120
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.1299 - val_accuracy: 0.9633 - val_loss: 0.2027 - learning_rate: 5.0000e-05
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9567 - loss: 0.2344
Test Loss : 0.23439203202724457
Test Accuracy : 0.9566666483879089

In [30]:
test_loss, test_accuracy = model.evaluate(X_test_tfidf.toarray(), y_test) # Corrected: Use TF-IDF test data converted to dense array

print("Test Loss :", test_loss)
print("Test Accuracy :", test_accuracy)

19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9567 - loss: 0.2344
Test Loss : 0.23439203202724457
Test Accuracy : 0.9566666483879089

In [31]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Prediksi data validasi
y_val_pred_ann = model.predict(X_val_tfidf.toarray(), verbose=0)

# Ubah probabilitas menjadi label 0 dan 1
y_val_pred_ann_binary = (y_val_pred_ann.ravel() >= 0.5).astype(int)

# Accuracy
accuracy_val_ann = accuracy_score(y_val, y_val_pred_ann_binary)

print("Accuracy Validation ANN:")
print(accuracy_val_ann)

print("\nClassification Report Validation ANN:")
print(classification_report(y_val, y_val_pred_ann_binary))

print("\nConfusion Matrix Validation ANN:")
print(confusion_matrix(y_val, y_val_pred_ann_binary))

Accuracy Validation ANN:
0.9633333333333334

Classification Report Validation ANN:
              precision    recall  f1-score   support

           0       0.98      0.95      0.97       320
           1       0.95      0.97      0.96       280

    accuracy                           0.96       600
   macro avg       0.96      0.96      0.96       600
weighted avg       0.96      0.96      0.96       600


Confusion Matrix Validation ANN:
[[305  15]
 [  7 273]]

In [32]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Prediksi data testing
y_test_pred_ann = model.predict(X_test_tfidf.toarray(), verbose=0)

# Ubah probabilitas menjadi label 0 dan 1
y_test_pred_ann_binary = (y_test_pred_ann.ravel() >= 0.5).astype(int)

# Accuracy
accuracy_test_ann = accuracy_score(y_test, y_test_pred_ann_binary)

print("Accuracy Testing ANN:")
print(accuracy_test_ann)

print("\nClassification Report Testing ANN:")
print(classification_report(y_test, y_test_pred_ann_binary))

print("\nConfusion Matrix Testing ANN:")
print(confusion_matrix(y_test, y_test_pred_ann_binary))

Accuracy Testing ANN:
0.9566666666666667

Classification Report Testing ANN:
              precision    recall  f1-score   support

           0       0.96      0.96      0.96       320
           1       0.95      0.96      0.95       280

    accuracy                           0.96       600
   macro avg       0.96      0.96      0.96       600
weighted avg       0.96      0.96      0.96       600


Confusion Matrix Testing ANN:
[[306  14]
 [ 12 268]]

In [37]:
# Simpan TF-IDF
import pickle

with open("tfidf.pkl", "wb") as f:
    pickle.dump(vectorizer, f)

# Simpan model ANN
model.save("model_ann.keras")